#BNF+IAT 1.0 UTF-8;

/*(学习|模仿)动作；
  (学习|模仿)手势；
  (学习|模仿)姿势；
*/

!grammar call;
!slot <activity>;
!slot <other>;
!slot <sleep>;

!start <Commands>;
<Commands>:<command1> | <command2>

<command1>:[开始](学习!id(101)|模仿!id(101))<activity>;
<activity>: 动作!id(10001)|手势!id(10001)|姿势!id(10001);

<command2>:<sleep>;
<sleep>: 休眠!id(10000)|睡觉!id(10000)|关机!id(10000)|你可以滚了!id(10000)|退下!id(10000);





