#BNF+IAT 1.0 UTF-8;

!grammar call;
!slot <name>;
!start <commands>;
<commands>:(找一下|打电话给) <name>;
<name>: 张三|李四;

/*!grammar wakeup;
!slot <key_words>;

start <comments>;

<comments>:小茜小茜;*/

